name: Deploy Server to EC2

on:
    push:
        branches:
            - j-047-ci-cd
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Test
              run: npm run test

            - name: Build
              run: npm run build

    deploy:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Deploy to EC2
              run: |
                  ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ env.DOMAIN }} << 'ENDSSH'
                    cd /jchatserver
                    git pull
                    npm install
                    npm run build
                    pm2 restart ecosystem.config.js
                  ENDSSH
